### PR TITLE
We do a bit of cleanup

### PR DESCRIPTION
**Pull request by valkyrienyanko**

### CODE REVIEW

**Review by QueenOfSquiggles — CHANGES_REQUESTED** [review]
To merge this in, I'd greatly prefer that any global usings were placed in a separate file as opposed to the Player Controller. Mostly just a style preference. The player controlller feels like a rather arbitrary place to put them. Otherwise, thanks a ton for all the cleanup you did!

**Review by QueenOfSquiggles — APPROVED** [review]
This works great. Can't believe I missed purging it all from the repo!

**Comment by QueenOfSquiggles** [comment]
Oh no I thought I could review on individual commits. I'm gonna make a single large review I guess LOL

**Review by QueenOfSquiggles — CHANGES_REQUESTED** [review]
Most everything looks pretty good. I've got a few questions/requirements before merging in.

For [866df71](https://github.com/QueenOfSquiggles/WhereTheDeadLie/pull/2/commits/866df711a9975d07049650d613565d6700eded02), I'd like global usings to be moved into a single separate file. The choice to place them in the Player Controller feels rather arbitrary.

For [42e5b02](https://github.com/QueenOfSquiggles/WhereTheDeadLie/pull/2/commits/42e5b02015962c7f7dbba014c3bc315f633d345c), I feel like this is a code style preference. I personally find it more readable to have the one-line methods not have method bodies. But if this is a formal code style that is more standard for C# then I'm happy to accept the change.

Otherwise everything is really good. I never expected anyone to go in and clean up my code so I wanna say thanks again and again!

**Comment by valkyrienyanko** [comment]
I reverted the one-liners and moved the global usings to another file.

**Review by QueenOfSquiggles — APPROVED** [review]
Thanks a ton. You did some real great work! Approved

**Pull request merged**
